[[layers]]
type = "3D"
[[layers.entities]]
name = "s_cube"
type = "static"
[layers.entities.overrides]
[[layers.entities.overrides.transform]]
1 = 2
2 = 0
3 = 0
4 = 0
[[layers.entities.overrides.transform]]
1 = 0
2 = 2
3 = 0
4 = 0
[[layers.entities.overrides.transform]]
1 = 0
2 = 0
3 = 2
4 = 0
[[layers.entities.overrides.transform]]
1 = 0
2 = 0
3 = 0
4 = 1
[[layers]]
type = "2D"


