return {
  layers={
    {
      type="3D",
      entities={
        {
          type="static",
          name="s_cube",
          overrides={
            transform={
              {2,0,0,0},
              {0,2,0,0},
              {0,0,2,0},
              {0,0,0,1}
            }
          }
        }
      }
    },
    {
      type="2D",
      entities={}
    }
  }
}